# IDs for the game objects
TID_PLAYER = 0
TID_PROTESTER = 1
TID_HARD_CORE_PROTESTER = 2
TID_WATER_SPURT = 3
TID_BOULDER = 4
TID_BARREL = 5
TID_EARTH = 6
TID_GOLD = 7
TID_SONAR = 8
TID_WATER_POOL = 9

# sounds
SOUND_THEME = 0
SOUND_PROTESTER_GIVE_UP = 1
SOUND_PLAYER_GIVE_UP = 2
SOUND_PROTESTER_YELL = 3
SOUND_PLAYER_SQUIRT = 4
SOUND_GOT_GOODIE = 5
SOUND_DIG = 6
SOUND_FINISHED_LEVEL = 7
SOUND_FOUND_OIL = 8
SOUND_PROTESTER_ANNOYED = 9
SOUND_PLAYER_ANNOYED = 10
SOUND_PROTESTER_FOUND_GOLD = 11
SOUND_SONAR = 12
SOUND_FALLING_ROCK = 13
SOUND_NONE = -1

# board and sprite dimensions
VIEW_WIDTH = 64
VIEW_HEIGHT = 64

# need to be bigger
SPRITE_WIDTH = 12
SPRITE_HEIGHT = 12

EARTH_WIDTH = 12
EARTH_HEIGHT = 12

# windows size
WINDOW_WIDTH = 768
WINDOW_HEIGHT = 768

# colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# fonts
FONT = "timesnewroman"
FONT_SIZE = 32

FPS = 60
